version: "3.9"
services:
  web:
    build: web/
    ports:
      - "4200:4200" 

  service-assignment:
    build: server/assignments-service/
    ports:
      - "9093:9093"
    links:
      - bd

  service-employee:
    build: server/employee-service/
    ports:
      - "9091:9091"
    links:
      - bd


      
  bd:
    image: mongo:5.0 
    ports:
      - "27017:27017"