version: "3.9"
services:

  web:
    restart: always
    build: web/
    ports:
      - "4200:80"

  service-assignment:
    restart: always
    build: server/assignments-service/
    ports:
      - "9093:9093"
    links:
      - mongo

  service-employee:
    restart: always
    build: server/employee-service/
    ports:
      - "9091:9091"
    links:
      - mongo
    
  service-performance:
    build: server/perfomance-service/
    ports:
      - "9092:9092"
    links:
      - mongo  

  mongo:
    container_name: mongo
    image: mongo:5.0 
    ports:
      - "27017:27017"